### ISSUE TITLE
Per user access rights

### ISSUE THREAD

**Issue by reklatsmasters** [reklatsmasters/verdaccio-github-token#1]
```yml
auth:
  github-token:
    org: nodertc
    ttl: 3600000 # 1h in ms
    permissions:
      reklatsmasters:	// should be a member of the organisation
        access: true
        publish: false
      '*':	// all other users in org
        access: true
        publish: true
```
